# == In this configuration, you set up Alchemy's element layouts.
#
# For further information please see http://guides.alchemy-cms.com/stable/elements.html

- name: article
  hint: true
  unique: true
  contents:
  - name: headline
    type: EssenceText
    default: :article_headline
    hint: true
  - name: picture
    type: EssencePicture
    hint: true
  - name: text
    type: EssenceRichtext
    default: :article_text
    hint: true

- name: main_title
  unique: true
  contents:
  - name: h1
    type: EssenceText
    default: :main_title
    hint: true
  - name: h2
    type: EssenceText
    default: :main_title
    hint: true

- name: motd
  unique: true
  contents:
  - name: motd_text
    type: EssenceText
    default: motd_text
    hint: true

- name: product
  contents:
  - name: name
    type: EssenceText
    default: 'Product Title'
    hint: true
  - name: description
    type: EssenceText
    default: 'Product Description'
  - name: price
    type: EssenceText
  - name: picture
    type: EssencePicture
