# == This file defines the page layouts for new pages.
#
# For further information please see http://guides.alchemy-cms.com/stable/page_layouts.html

- name: home
  unique: true
  elements: [main_title]
  autogenerate: [main_title]

- name: products_thumbnails
  elements: [service]

- name: products_portfolio
  unique: true
  elements: [product]

# global pages

- name: header
  unique: true
  layoutpage: true
  elements: [motd]
  autogenerate: [motd]

